language: scala
sudo: false

scala:
  - 2.13.0
  - 2.12.8

jdk:
  - openjdk8

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 10
  - nvm use 10
  - export NODE_PATH="$(npm config get prefix)"/lib/node_modules
  - npm install
  - npm install jsdom@9.12.0 source-map-support

script:
  #- sbt ++$TRAVIS_SCALA_VERSION test:fastOptJS test:fullOptJS
  - sbt ++$TRAVIS_SCALA_VERSION 'set parallelExecution in ThisBuild := false' test
  - sbt ++$TRAVIS_SCALA_VERSION 'set parallelExecution in ThisBuild := false' 'set scalaJSStage in ThisBuild := FullOptStage' test
  - bin/checkDevOnly $TRAVIS_SCALA_VERSION

before_cache:
  - rm -f $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.sbt -name "*.lock" -type f -delete
cache:
  directories:
    - $HOME/.coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

