language: scala
sudo: false

jobs:
  include:

    - name: 'Scala 2.12 / Scala.JS 0.6 / Java 8'
      scala: 2.12.11
      jdk: openjdk8
      env: SCALAJS_VERSION=0.6.32

    - name: 'Scala 2.13 / Scala.JS 0.6 / Java 8'
      scala: 2.13.2
      jdk: openjdk8
      env: SCALAJS_VERSION=0.6.32

    - name: 'Scala 2.12 / Scala.JS 1.0 / Java 11'
      scala: 2.12.11
      jdk: openjdk11
      env: SCALAJS_VERSION=

    - name: 'Scala 2.13 / Scala.JS 1.0 / Java 11'
      scala: 2.13.2
      jdk: openjdk11
      env: SCALAJS_VERSION=

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 14
  - nvm use 14
  - export NODE_PATH="$(npm config get prefix)"/lib/node_modules
  - npm install
  - npm install jsdom source-map-support

script:
  #- sbt ++$TRAVIS_SCALA_VERSION test:fastOptJS test:fullOptJS
  - sbt ++$TRAVIS_SCALA_VERSION 'set parallelExecution in ThisBuild := false' test
  - sbt ++$TRAVIS_SCALA_VERSION 'set parallelExecution in ThisBuild := false' 'set scalaJSStage in ThisBuild := FullOptStage' test
  - bin/checkDevOnly $TRAVIS_SCALA_VERSION

before_cache:
  - rm -f $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.sbt -name "*.lock" -type f -delete
cache:
  directories:
    - $HOME/.coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

