language: scala
sudo: false

jobs:
  include:

    - name: 'Scala 2.13 / Java 11'
      scala: 2.13.6
      jdk: openjdk11

    - name: 'Scala 3.0.0-RC3 / Java 11'
      scala: 3.0.0-RC3
      jdk: openjdk11

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 14
  - nvm use 14
  - export NODE_PATH="$(npm config get prefix)"/lib/node_modules
  - npm install
  - npm install jsdom source-map-support
  - |
    # update this only when sbt-the-bash-script needs to be updated
    export SBT_LAUNCHER=1.5.2
    export SBT_OPTS="-Dfile.encoding=UTF-8"
    curl -L --silent "https://github.com/sbt/sbt/releases/download/v$SBT_LAUNCHER/sbt-$SBT_LAUNCHER.tgz" > $HOME/sbt.tgz
    tar zxf $HOME/sbt.tgz -C $HOME
    sudo rm /usr/local/bin/sbt
    sudo ln -s $HOME/sbt/bin/sbt /usr/local/bin/sbt

script:
  - bin/ci

before_cache:
  - rm -f $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.sbt -name "*.lock" -type f -delete
cache:
  directories:
    - $HOME/.coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt
